### Converting Given Data To Tensor 
1. In PyTorch, the philosophy is "Explicit is better than implicit." PyTorch generally requires you to manually ensure your data is a torch.Tensor before it enters a model or a specialized data utility.
2. For General Data (Numbers): You usually just use torch.tensor(my_numpy_array).

3. For Images: PyTorch uses transforms.ToTensor(). This does two special things that TensorFlow's basic loading doesn't do automatically:

        1. Permutes Dimensions: It changes an image from (Height, Width, Channels) to (Channels, Height, Width), which is the standard PyTorch format.

        2. Normalizes: It scales pixel values from 0–255 to 0.0–1.0.

In [ ]:
import torch
import numpy as np
arr1 = np.array([1,2,3,4,5]).reshape(5,1)
t1  = torch.tensor(arr1)     # both tensor and Tensor makes tensor but difference is in the dtype!!! Furthermore tensor is the function which can be used for converting numpy arrays whereas Tensor is a Class and it can be used to create tensors directly like torch.Tensor([1,2,3,4])
print(t1.shape)            # tensor() is similar to tf.constant i.e. immutable whereas for parameters which are to be updated during training nn.Parameter can be used 
print(t1)
print("After Flattening")
t1 = t1.flatten()
print(t1.shape)
print(t1)

torch.Size([5, 1])
tensor([[1],
        [2],
        [3],
        [4],
        [5]])
After Flattening
torch.Size([5])
tensor([1, 2, 3, 4, 5])


In [ ]:
# torch.tensor() creates a seperate copy of the numpy array in memory which is use as tensor 
# but torch.from_numpy() creates a tensor which shares the memory with numpy array i.e. point to same underlying buffer 
array = np.array([1,2,3,4,5])
ten = torch.from_numpy(array) # if i add.float() here , now the datatype is different so it will create a seperate memory location for the tensor and thus chnages wont reflect anymore !!!
array[2] = 9
print(ten)

tensor([1, 2, 9, 4, 5])


### DataPipelines

In [1]:

from torch.utils.data import TensorDataset, DataLoader

features_pt = torch.randn(100, 8)
label_pt = torch.randn(100, 1) # already creates tensors

dataset = TensorDataset(features_pt, label_pt)
dataloader = DataLoader(dataset,batch_size = 32, shuffle = True)

print("Pytorch Dataset Ready!!!")

 

Pytorch Dataset Ready!!!


### Model

In [4]:
import torch.nn as nn
import torch.optim as optim

class SimpleNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(8,16)      # Linear is for torch as how Dense is for tensorflow 
        self.output = nn.Linear(16,1)
        self.relu = nn.ReLU()
    def forward(self, x):
        output = self.relu(self.hidden(x))
        output = self.output(output)
        return output

model_pt = SimpleNet()
criterion = nn.MSELoss()   # for regression 
optimizer = optim.Adam(model_pt.parameters(), lr=0.001)

### Training Mechanics

In [ ]:
model_pt.train()
best_loss = float('inf')
patience = 3
counter = 0
for epoch in range(10):
    for data, target in dataloader:
        optimizer.zero_grad()
        output = model_pt(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
    # for data, target in testloader:       # here as we did not have test and train data seperately so the same train dataset is used for early stopping , but in actual scenerio val_loss is calculated via test loader and then early stopping is checked
        if loss < best_loss:
            best_loss = loss
            counter = 0
            torch.save(model_pt.state_dict(), 'best_model.pt')
        else:
            counter += 1
            if counter >= patience:
                print("Early Stopping Triggered")
                break

In [11]:
print(type(float('inf')))
Y_test = np.random.random((10,1))
Y_test.flatten().shape
type(Y_test)

<class 'float'>


numpy.ndarray